fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\Utilisateur
  from_email:
    address: 'email@gmail.com' # for example your email
    sender_name: 'email@gmail.com' # for example your email