services:
    Pusher\Pusher:
        public: true
        arguments:
            - '%env(PUSHER_APP_KEY)%'
            - '%env(PUSHER_APP_SECRET)%'
            - '%env(PUSHER_APP_ID)%'
            - { cluster: '%env(PUSHER_CLUSTER)%' }

lopi_pusher:
    key: '%env(PUSHER_APP_KEY)%'
    secret: '%env(PUSHER_APP_SECRET)%'
    app_id: '%env(PUSHER_APP_ID)%'
    cluster: '%env(PUSHER_CLUSTER)%'